# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='pta',
        ),
        migrations.AddField(
            model_name='ptaboard',
            name='school',
            field=models.ManyToManyField(to='saas.School'),
        ),
    ]
