# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_remove_judge_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
