# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_auto_20161106_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='asignee',
        ),
    ]
