# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_remove_task_asignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='asignee',
            field=models.ManyToManyField(blank=True, null=True, to='saas.Volunteer'),
        ),
    ]
