# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0014_auto_20161112_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='school',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
