# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0017_auto_20161112_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='image',
        ),
        migrations.AddField(
            model_name='image_logo',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.School'),
        ),
    ]
