# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0021_auto_20161113_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='expense_amount',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='expense_date',
        ),
    ]
