# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0022_auto_20161115_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='expense_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='expense_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
