# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0024_remove_child_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.School'),
        ),
    ]
