# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0025_child_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='child',
        ),
    ]
